version: '3'
services:
  webdav:
    image: jadinheaston/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: Alice
      PASSWORD: Secret1234!
    volumes:
      - webdav-data:/var/lib/dav